#!/usr/bin/env zsh
export PATH="/opt/homebrew/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.cargo/env ] && source ~/.cargo/env

alias cat="bat"
alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias e="code"
alias h="cd ~"
alias l="eza --git --icons -alh"
alias vi="nvim"

eval "$(mise activate zsh)"
# 1Password shell plugins (brew, etc.)
[ -s "$HOME/.config/op/plugins.sh" ] && source "$HOME/.config/op/plugins.sh"

eval "$(starship init zsh)"

