#!/usr/bin/env zsh
export PATH="/opt/homebrew/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.cargo/env ] && source ~/.cargo/env

alias cat="bat"
alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias e="code"
alias h="cd ~"
alias l="exa --git --icons -alh"
alias vi="nvim"

eval "$(starship init zsh)"

